-- ----------------------------
-- 1、init tb_function (非国密)
-- ----------------------------
-- (system config info 0x1000) setValueByKey
INSERT INTO `tb_function`(`method_id`, `abi_info`, `type`, `gmt_create`, `gmt_modify`) VALUES ('0xbd291aef', '{\"constant\":false,\"inputs\":[{\"name\":\"key\",\"type\":\"string\"},{\"name\":\"value\",\"type\":\"string\"}],\"name\":\"setValueByKey\",\"outputs\":[{\"name\":\"\",\"type\":\"int256\"}],\"payable\":false,\"stateMutability\":\"nonpayable\",\"type\":\"function\"}', 'function', now(), now());
-- (table factory 0x1001) createTable openTable
INSERT INTO `tb_function`(`method_id`, `abi_info`, `type`, `gmt_create`, `gmt_modify`) VALUES ('0x56004b6a', '{\"constant\":false,\"inputs\":[{\"name\":\"tableName\",\"type\":\"string\"},{\"name\":\"key\",\"type\":\"string\"},{\"name\":\"valueField\",\"type\":\"string\"}],\"name\":\"createTable\",\"outputs\":[{\"name\":\"\",\"type\":\"int256\"}],\"payable\":false,\"stateMutability\":\"nonpayable\",\"type\":\"function\"}', 'function', now(), now());
INSERT INTO `tb_function`(`method_id`, `abi_info`, `type`, `gmt_create`, `gmt_modify`) VALUES ('0xf23f63c9', '{\"constant\":true,\"inputs\":[{\"name\":\"\",\"type\":\"string\"}],\"name\":\"openTable\",\"outputs\":[{\"name\":\"\",\"type\":\"address\"}],\"payable\":false,\"stateMutability\":\"view\",\"type\":\"function\"}', 'function', now(), now());
-- (crud info 0x1002) update select remove insert(same as cns's insert)
INSERT INTO `tb_function`(`method_id`, `abi_info`, `type`, `gmt_create`, `gmt_modify`) VALUES ('0x2dca76c1', '{\"constant\":false,\"inputs\":[{\"name\":\"tableName\",\"type\":\"string\"},{\"name\":\"key\",\"type\":\"string\"},{\"name\":\"entry\",\"type\":\"string\"},{\"name\":\"condition\",\"type\":\"string\"},{\"name\":\"optional\",\"type\":\"string\"}],\"name\":\"update\",\"outputs\":[{\"name\":\"\",\"type\":\"int256\"}],\"payable\":false,\"stateMutability\":\"nonpayable\",\"type\":\"function\"}', 'function', now(), now());
INSERT INTO `tb_function`(`method_id`, `abi_info`, `type`, `gmt_create`, `gmt_modify`) VALUES ('0x983c6c4f', '{\"constant\":true,\"inputs\":[{\"name\":\"tableName\",\"type\":\"string\"},{\"name\":\"key\",\"type\":\"string\"},{\"name\":\"condition\",\"type\":\"string\"},{\"name\":\"optional\",\"type\":\"string\"}],\"name\":\"select\",\"outputs\":[{\"name\":\"\",\"type\":\"string\"}],\"payable\":false,\"stateMutability\":\"view\",\"type\":\"function\"}', 'function', now(), now());
INSERT INTO `tb_function`(`method_id`, `abi_info`, `type`, `gmt_create`, `gmt_modify`) VALUES ('0xa72a1e65', '{\"constant\":false,\"inputs\":[{\"name\":\"tableName\",\"type\":\"string\"},{\"name\":\"key\",\"type\":\"string\"},{\"name\":\"condition\",\"type\":\"string\"},{\"name\":\"optional\",\"type\":\"string\"}],\"name\":\"remove\",\"outputs\":[{\"name\":\"\",\"type\":\"int256\"}],\"payable\":false,\"stateMutability\":\"nonpayable\",\"type\":\"function\"}', 'function', now(), now());
INSERT INTO `tb_function`(`method_id`, `abi_info`, `type`, `gmt_create`, `gmt_modify`) VALUES ('0xa216464b', '{\"constant\":false,\"inputs\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"version\",\"type\":\"string\"},{\"name\":\"addr\",\"type\":\"string\"},{\"name\":\"abi\",\"type\":\"string\"}],\"name\":\"insert\",\"outputs\":[{\"name\":\"\",\"type\":\"int256\"}],\"payable\":false,\"stateMutability\":\"nonpayable\",\"type\":\"function\"}', 'function', now(), now());
-- (consensus info node manage 0x1003) addObserver addSealer remove
INSERT INTO `tb_function`(`method_id`, `abi_info`, `type`, `gmt_create`, `gmt_modify`) VALUES ('0x2800efc0', '{\"constant\":false,\"inputs\":[{\"name\":\"nodeID\",\"type\":\"string\"}],\"name\":\"addObserver\",\"outputs\":[{\"name\":\"\",\"type\":\"int256\"}],\"payable\":false,\"stateMutability\":\"nonpayable\",\"type\":\"function\"}', 'function', now(), now());
INSERT INTO `tb_function`(`method_id`, `abi_info`, `type`, `gmt_create`, `gmt_modify`) VALUES ('0x89152d1f', '{\"constant\":false,\"inputs\":[{\"name\":\"nodeID\",\"type\":\"string\"}],\"name\":\"addSealer\",\"outputs\":[{\"name\":\"\",\"type\":\"int256\"}],\"payable\":false,\"stateMutability\":\"nonpayable\",\"type\":\"function\"}', 'function', now(), now());
INSERT INTO `tb_function`(`method_id`, `abi_info`, `type`, `gmt_create`, `gmt_modify`) VALUES ('0x80599e4b', '{\"constant\":false,\"inputs\":[{\"name\":\"nodeID\",\"type\":\"string\"}],\"name\":\"remove\",\"outputs\":[{\"name\":\"\",\"type\":\"int256\"}],\"payable\":false,\"stateMutability\":\"nonpayable\",\"type\":\"function\"}', 'function', now(), now());
-- (cns info 0x1004) selectByName selectByNameAndVersion // insert(ignored, same as crud's insert method: insert(string,string,string,string)
INSERT INTO `tb_function`(`method_id`, `abi_info`, `type`, `gmt_create`, `gmt_modify`) VALUES ('0x819a3d62', '{\"constant\":true,\"inputs\":[{\"name\":\"name\",\"type\":\"string\"}],\"name\":\"selectByName\",\"outputs\":[{\"name\":\"\",\"type\":\"string\"}],\"payable\":false,\"stateMutability\":\"view\",\"type\":\"function\"}', 'function', now(), now());
INSERT INTO `tb_function`(`method_id`, `abi_info`, `type`, `gmt_create`, `gmt_modify`) VALUES ('0x897f0251', '{\"constant\":true,\"inputs\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"version\",\"type\":\"string\"}],\"name\":\"selectByNameAndVersion\",\"outputs\":[{\"name\":\"\",\"type\":\"string\"}],\"payable\":false,\"stateMutability\":\"view\",\"type\":\"function\"}', 'function', now(), now());
-- INSERT INTO `tb_function`(`method_id`, `abi_info`, `type`, `gmt_create`, `gmt_modify`) VALUES ('0xa216464b', '{\"constant\":false,\"inputs\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"version\",\"type\":\"string\"},{\"name\":\"addr\",\"type\":\"string\"},{\"name\":\"abi\",\"type\":\"string\"}],\"name\":\"insert\",\"outputs\":[{\"name\":\"\",\"type\":\"int256\"}],\"payable\":false,\"stateMutability\":\"nonpayable\",\"type\":\"function\"}', 'function', now(), now());
-- (permission manage 0x1005) insert queryByName remove grantWrite revokeWrite
INSERT INTO `tb_function`(`method_id`, `abi_info`, `type`, `gmt_create`, `gmt_modify`) VALUES ('0x06e63ff8', '{\"constant\":false,\"inputs\":[{\"name\":\"table_name\",\"type\":\"string\"},{\"name\":\"addr\",\"type\":\"string\"}],\"name\":\"insert\",\"outputs\":[{\"name\":\"\",\"type\":\"int256\"}],\"payable\":false,\"stateMutability\":\"nonpayable\",\"type\":\"function\"}', 'function', now(), now());
INSERT INTO `tb_function`(`method_id`, `abi_info`, `type`, `gmt_create`, `gmt_modify`) VALUES ('0x20586031', '{\"constant\":true,\"inputs\":[{\"name\":\"table_name\",\"type\":\"string\"}],\"name\":\"queryByName\",\"outputs\":[{\"name\":\"\",\"type\":\"string\"}],\"payable\":false,\"stateMutability\":\"view\",\"type\":\"function\"}', 'function', now(), now());
INSERT INTO `tb_function`(`method_id`, `abi_info`, `type`, `gmt_create`, `gmt_modify`) VALUES ('0x44590a7e', '{\"constant\":false,\"inputs\":[{\"name\":\"table_name\",\"type\":\"string\"},{\"name\":\"addr\",\"type\":\"string\"}],\"name\":\"remove\",\"outputs\":[{\"name\":\"\",\"type\":\"int256\"}],\"payable\":false,\"stateMutability\":\"nonpayable\",\"type\":\"function\"}', 'function', now(), now());
INSERT INTO `tb_function`(`method_id`, `abi_info`, `type`, `gmt_create`, `gmt_modify`) VALUES ('0x96ec37c4', '{\"constant\":false,\"inputs\":[{\"name\":\"contractAddr\",\"type\":\"address\"},{\"name\":\"user\",\"type\":\"address\"}],\"name\":\"grantWrite\",\"outputs\":[{\"name\":\"\",\"type\":\"int256\"}],\"payable\":false,\"stateMutability\":\"nonpayable\",\"type\":\"function\"}', 'function', now(), now());
INSERT INTO `tb_function`(`method_id`, `abi_info`, `type`, `gmt_create`, `gmt_modify`) VALUES ('0x99c26010', '{\"constant\":false,\"inputs\":[{\"name\":\"contractAddr\",\"type\":\"address\"},{\"name\":\"user\",\"type\":\"address\"}],\"name\":\"revokeWrite\",\"outputs\":[{\"name\":\"\",\"type\":\"int256\"}],\"payable\":false,\"stateMutability\":\"nonpayable\",\"type\":\"function\"}', 'function', now(), now());
-- (contract life cycle 0x1007)
-- getStatus unfreeze freeze grantManager queryManager revokeManager
INSERT INTO `tb_function`(`method_id`, `abi_info`, `type`, `gmt_create`, `gmt_modify`) VALUES ('0x30ccebb5', '{\"constant\":true,\"inputs\":[{\"name\":\"addr\",\"type\":\"address\"}],\"name\":\"getStatus\",\"outputs\":[{\"name\":\"\",\"type\":\"uint256\"},{\"name\":\"\",\"type\":\"string\"}],\"payable\":false,\"stateMutability\":\"view\",\"type\":\"function\"}', 'function', now(), now());
INSERT INTO `tb_function`(`method_id`, `abi_info`, `type`, `gmt_create`, `gmt_modify`) VALUES ('0x45c8b1a6', '{\"constant\":false,\"inputs\":[{\"name\":\"addr\",\"type\":\"address\"}],\"name\":\"unfreeze\",\"outputs\":[{\"name\":\"\",\"type\":\"int256\"}],\"payable\":false,\"stateMutability\":\"nonpayable\",\"type\":\"function\"}', 'function', now(), now());
INSERT INTO `tb_function`(`method_id`, `abi_info`, `type`, `gmt_create`, `gmt_modify`) VALUES ('0x8d1fdf2f', '{\"constant\":false,\"inputs\":[{\"name\":\"addr\",\"type\":\"address\"}],\"name\":\"freeze\",\"outputs\":[{\"name\":\"\",\"type\":\"int256\"}],\"payable\":false,\"stateMutability\":\"nonpayable\",\"type\":\"function\"}', 'function', now(), now());
INSERT INTO `tb_function`(`method_id`, `abi_info`, `type`, `gmt_create`, `gmt_modify`) VALUES ('0xa721fb43', '{\"constant\":false,\"inputs\":[{\"name\":\"contractAddr\",\"type\":\"address\"},{\"name\":\"userAddr\",\"type\":\"address\"}],\"name\":\"grantManager\",\"outputs\":[{\"name\":\"\",\"type\":\"int256\"}],\"payable\":false,\"stateMutability\":\"nonpayable\",\"type\":\"function\"}', 'function', now(), now());
INSERT INTO `tb_function`(`method_id`, `abi_info`, `type`, `gmt_create`, `gmt_modify`) VALUES ('0xbc92a700', '{\"constant\":true,\"inputs\":[{\"name\":\"addr\",\"type\":\"address\"}],\"name\":\"queryManager\",\"outputs\":[{\"name\":\"\",\"type\":\"uint256\"},{\"name\":\"\",\"type\":\"address[]\"}],\"payable\":false,\"stateMutability\":\"view\",\"type\":\"function\"}', 'function', now(), now());
INSERT INTO `tb_function`(`method_id`, `abi_info`, `type`, `gmt_create`, `gmt_modify`) VALUES ('0x3a67288f', '{\"constant\":false,\"inputs\":[{\"name\":\"contractAddr\",\"type\":\"address\"},{\"name\":\"userAddr\",\"type\":\"address\"}],\"name\":\"revokeManager\",\"outputs\":[{\"name\":\"\",\"type\":\"int256\"}],\"payable\":false,\"stateMutability\":\"nonpayable\",\"type\":\"function\"}', 'function', now(), now());
-- (chain governance 0x1008)
-- listOperators updateCommitteeMemberWeight queryThreshold queryCommitteeMemberWeight grantCommitteeMember
INSERT INTO `tb_function`(`method_id`, `abi_info`, `type`, `gmt_create`, `gmt_modify`) VALUES ('0x039a93ca', '{\"constant\":true,\"inputs\":[],\"name\":\"listOperators\",\"outputs\":[{\"name\":\"\",\"type\":\"string\"}],\"payable\":false,\"stateMutability\":\"view\",\"type\":\"function\"}', 'function', now(), now());
INSERT INTO `tb_function`(`method_id`, `abi_info`, `type`, `gmt_create`, `gmt_modify`) VALUES ('0x246c3376', '{\"constant\":false,\"inputs\":[{\"name\":\"user\",\"type\":\"address\"},{\"name\":\"weight\",\"type\":\"int256\"}],\"name\":\"updateCommitteeMemberWeight\",\"outputs\":[{\"name\":\"\",\"type\":\"int256\"}],\"payable\":false,\"stateMutability\":\"nonpayable\",\"type\":\"function\"}', 'function', now(), now());
INSERT INTO `tb_function`(`method_id`, `abi_info`, `type`, `gmt_create`, `gmt_modify`) VALUES ('0x281af27d', '{\"constant\":true,\"inputs\":[],\"name\":\"queryThreshold\",\"outputs\":[{\"name\":\"\",\"type\":\"int256\"}],\"payable\":false,\"stateMutability\":\"view\",\"type\":\"function\"}', 'function', now(), now());
INSERT INTO `tb_function`(`method_id`, `abi_info`, `type`, `gmt_create`, `gmt_modify`) VALUES ('0x6c147119', '{\"constant\":true,\"inputs\":[{\"name\":\"user\",\"type\":\"address\"}],\"name\":\"queryCommitteeMemberWeight\",\"outputs\":[{\"name\":\"\",\"type\":\"bool\"},{\"name\":\"\",\"type\":\"int256\"}],\"payable\":false,\"stateMutability\":\"view\",\"type\":\"function\"}', 'function', now(), now());
INSERT INTO `tb_function`(`method_id`, `abi_info`, `type`, `gmt_create`, `gmt_modify`) VALUES ('0x6f8f521f', '{\"constant\":false,\"inputs\":[{\"name\":\"user\",\"type\":\"address\"}],\"name\":\"grantCommitteeMember\",\"outputs\":[{\"name\":\"\",\"type\":\"int256\"}],\"payable\":false,\"stateMutability\":\"nonpayable\",\"type\":\"function\"}', 'function', now(), now());
-- unfreezeAccount listCommitteeMembers updateThreshold revokeCommitteeMember grantOperator
INSERT INTO `tb_function`(`method_id`, `abi_info`, `type`, `gmt_create`, `gmt_modify`) VALUES ('0x788649ea', '{\"constant\":false,\"inputs\":[{\"name\":\"account\",\"type\":\"address\"}],\"name\":\"unfreezeAccount\",\"outputs\":[{\"name\":\"\",\"type\":\"int256\"}],\"payable\":false,\"stateMutability\":\"nonpayable\",\"type\":\"function\"}', 'function', now(), now());
INSERT INTO `tb_function`(`method_id`, `abi_info`, `type`, `gmt_create`, `gmt_modify`) VALUES ('0x885a3a72', '{\"constant\":true,\"inputs\":[],\"name\":\"listCommitteeMembers\",\"outputs\":[{\"name\":\"\",\"type\":\"string\"}],\"payable\":false,\"stateMutability\":\"view\",\"type\":\"function\"}', 'function', now(), now());
INSERT INTO `tb_function`(`method_id`, `abi_info`, `type`, `gmt_create`, `gmt_modify`) VALUES ('0x97b00861', '{\"constant\":false,\"inputs\":[{\"name\":\"threshold\",\"type\":\"int256\"}],\"name\":\"updateThreshold\",\"outputs\":[{\"name\":\"\",\"type\":\"int256\"}],\"payable\":false,\"stateMutability\":\"nonpayable\",\"type\":\"function\"}', 'function', now(), now());
INSERT INTO `tb_function`(`method_id`, `abi_info`, `type`, `gmt_create`, `gmt_modify`) VALUES ('0xcafb4d1b', '{\"constant\":false,\"inputs\":[{\"name\":\"user\",\"type\":\"address\"}],\"name\":\"revokeCommitteeMember\",\"outputs\":[{\"name\":\"\",\"type\":\"int256\"}],\"payable\":false,\"stateMutability\":\"nonpayable\",\"type\":\"function\"}', 'function', now(), now());
INSERT INTO `tb_function`(`method_id`, `abi_info`, `type`, `gmt_create`, `gmt_modify`) VALUES ('0xe348da13', '{\"constant\":false,\"inputs\":[{\"name\":\"user\",\"type\":\"address\"}],\"name\":\"grantOperator\",\"outputs\":[{\"name\":\"\",\"type\":\"int256\"}],\"payable\":false,\"stateMutability\":\"nonpayable\",\"type\":\"function\"}', 'function', now(), now());
-- freezeAccount revokeOperator getAccountStatus
INSERT INTO `tb_function`(`method_id`, `abi_info`, `type`, `gmt_create`, `gmt_modify`) VALUES ('0xf26c159f', '{\"constant\":false,\"inputs\":[{\"name\":\"account\",\"type\":\"address\"}],\"name\":\"freezeAccount\",\"outputs\":[{\"name\":\"\",\"type\":\"int256\"}],\"payable\":false,\"stateMutability\":\"nonpayable\",\"type\":\"function\"}', 'function', now(), now());
INSERT INTO `tb_function`(`method_id`, `abi_info`, `type`, `gmt_create`, `gmt_modify`) VALUES ('0xfad8b32a', '{\"constant\":false,\"inputs\":[{\"name\":\"user\",\"type\":\"address\"}],\"name\":\"revokeOperator\",\"outputs\":[{\"name\":\"\",\"type\":\"int256\"}],\"payable\":false,\"stateMutability\":\"nonpayable\",\"type\":\"function\"}', 'function', now(), now());
INSERT INTO `tb_function`(`method_id`, `abi_info`, `type`, `gmt_create`, `gmt_modify`) VALUES ('0xfd4fa05a', '{\"constant\":true,\"inputs\":[{\"name\":\"account\",\"type\":\"address\"}],\"name\":\"getAccountStatus\",\"outputs\":[{\"name\":\"\",\"type\":\"string\"}],\"payable\":false,\"stateMutability\":\"view\",\"type\":\"function\"}', 'function', now(), now());

-- ----------------------------
-- 2. init tb_function (国密)
-- ----------------------------
-- (system config info 0x1000) setValueByKey
INSERT INTO `tb_function`(`method_id`, `abi_info`, `type`, `gmt_create`, `gmt_modify`) VALUES ('0x0749b518', '{\"constant\":false,\"inputs\":[{\"name\":\"key\",\"type\":\"string\"},{\"name\":\"value\",\"type\":\"string\"}],\"name\":\"setValueByKey\",\"outputs\":[{\"name\":\"\",\"type\":\"int256\"}],\"payable\":false,\"stateMutability\":\"nonpayable\",\"type\":\"function\"}', 'function', now(), now());
-- (table factory 0x1001) createTable openTable
INSERT INTO `tb_function`(`method_id`, `abi_info`, `type`, `gmt_create`, `gmt_modify`) VALUES ('0xc92a7801', '{\"constant\":false,\"inputs\":[{\"name\":\"tableName\",\"type\":\"string\"},{\"name\":\"key\",\"type\":\"string\"},{\"name\":\"valueField\",\"type\":\"string\"}],\"name\":\"createTable\",\"outputs\":[{\"name\":\"\",\"type\":\"int256\"}],\"payable\":false,\"stateMutability\":\"nonpayable\",\"type\":\"function\"}', 'function', now(), now());
INSERT INTO `tb_function`(`method_id`, `abi_info`, `type`, `gmt_create`, `gmt_modify`) VALUES ('0x59a48b65', '{\"constant\":true,\"inputs\":[{\"name\":\"\",\"type\":\"string\"}],\"name\":\"openTable\",\"outputs\":[{\"name\":\"\",\"type\":\"address\"}],\"payable\":false,\"stateMutability\":\"view\",\"type\":\"function\"}', 'function', now(), now());
-- (crud info 0x1002) update select remove insert(same as cns's insert)
INSERT INTO `tb_function`(`method_id`, `abi_info`, `type`, `gmt_create`, `gmt_modify`) VALUES ('0x10bd675b', '{\"constant\":false,\"inputs\":[{\"name\":\"tableName\",\"type\":\"string\"},{\"name\":\"key\",\"type\":\"string\"},{\"name\":\"entry\",\"type\":\"string\"},{\"name\":\"condition\",\"type\":\"string\"},{\"name\":\"optional\",\"type\":\"string\"}],\"name\":\"update\",\"outputs\":[{\"name\":\"\",\"type\":\"int256\"}],\"payable\":false,\"stateMutability\":\"nonpayable\",\"type\":\"function\"}', 'function', now(), now());
INSERT INTO `tb_function`(`method_id`, `abi_info`, `type`, `gmt_create`, `gmt_modify`) VALUES ('0x7388111f', '{\"constant\":true,\"inputs\":[{\"name\":\"tableName\",\"type\":\"string\"},{\"name\":\"key\",\"type\":\"string\"},{\"name\":\"condition\",\"type\":\"string\"},{\"name\":\"optional\",\"type\":\"string\"}],\"name\":\"select\",\"outputs\":[{\"name\":\"\",\"type\":\"string\"}],\"payable\":false,\"stateMutability\":\"view\",\"type\":\"function\"}', 'function', now(), now());
INSERT INTO `tb_function`(`method_id`, `abi_info`, `type`, `gmt_create`, `gmt_modify`) VALUES ('0x81b81824', '{\"constant\":false,\"inputs\":[{\"name\":\"tableName\",\"type\":\"string\"},{\"name\":\"key\",\"type\":\"string\"},{\"name\":\"condition\",\"type\":\"string\"},{\"name\":\"optional\",\"type\":\"string\"}],\"name\":\"remove\",\"outputs\":[{\"name\":\"\",\"type\":\"int256\"}],\"payable\":false,\"stateMutability\":\"nonpayable\",\"type\":\"function\"}', 'function', now(), now());
INSERT INTO `tb_function`(`method_id`, `abi_info`, `type`, `gmt_create`, `gmt_modify`) VALUES ('0xb8eaa08d', '{\"constant\":false,\"inputs\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"version\",\"type\":\"string\"},{\"name\":\"addr\",\"type\":\"string\"},{\"name\":\"abi\",\"type\":\"string\"}],\"name\":\"insert\",\"outputs\":[{\"name\":\"\",\"type\":\"int256\"}],\"payable\":false,\"stateMutability\":\"nonpayable\",\"type\":\"function\"}', 'function', now(), now());
-- (consensus info node manage 0x1003) addObserver addSealer remove
INSERT INTO `tb_function`(`method_id`, `abi_info`, `type`, `gmt_create`, `gmt_modify`) VALUES ('0x25e85d16', '{\"constant\":false,\"inputs\":[{\"name\":\"nodeID\",\"type\":\"string\"}],\"name\":\"addObserver\",\"outputs\":[{\"name\":\"\",\"type\":\"int256\"}],\"payable\":false,\"stateMutability\":\"nonpayable\",\"type\":\"function\"}', 'function', now(), now());
INSERT INTO `tb_function`(`method_id`, `abi_info`, `type`, `gmt_create`, `gmt_modify`) VALUES ('0xdf434acc', '{\"constant\":false,\"inputs\":[{\"name\":\"nodeID\",\"type\":\"string\"}],\"name\":\"addSealer\",\"outputs\":[{\"name\":\"\",\"type\":\"int256\"}],\"payable\":false,\"stateMutability\":\"nonpayable\",\"type\":\"function\"}', 'function', now(), now());
INSERT INTO `tb_function`(`method_id`, `abi_info`, `type`, `gmt_create`, `gmt_modify`) VALUES ('0x86b733f9', '{\"constant\":false,\"inputs\":[{\"name\":\"nodeID\",\"type\":\"string\"}],\"name\":\"remove\",\"outputs\":[{\"name\":\"\",\"type\":\"int256\"}],\"payable\":false,\"stateMutability\":\"nonpayable\",\"type\":\"function\"}', 'function', now(), now());
-- (cns info 0x1004) selectByName selectByNameAndVersion // insert(ignored, same as crud's insert method: insert(string,string,string,string)
INSERT INTO `tb_function`(`method_id`, `abi_info`, `type`, `gmt_create`, `gmt_modify`) VALUES ('0x078af4af', '{\"constant\":true,\"inputs\":[{\"name\":\"name\",\"type\":\"string\"}],\"name\":\"selectByName\",\"outputs\":[{\"name\":\"\",\"type\":\"string\"}],\"payable\":false,\"stateMutability\":\"view\",\"type\":\"function\"}', 'function', now(), now());
INSERT INTO `tb_function`(`method_id`, `abi_info`, `type`, `gmt_create`, `gmt_modify`) VALUES ('0xec72a422', '{\"constant\":true,\"inputs\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"version\",\"type\":\"string\"}],\"name\":\"selectByNameAndVersion\",\"outputs\":[{\"name\":\"\",\"type\":\"string\"}],\"payable\":false,\"stateMutability\":\"view\",\"type\":\"function\"}', 'function', now(), now());
-- INSERT INTO `tb_function`(`method_id`, `abi_info`, `type`, `gmt_create`, `gmt_modify`) VALUES ('0xb8eaa08d', '{\"constant\":false,\"inputs\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"version\",\"type\":\"string\"},{\"name\":\"addr\",\"type\":\"string\"},{\"name\":\"abi\",\"type\":\"string\"}],\"name\":\"insert\",\"outputs\":[{\"name\":\"\",\"type\":\"int256\"}],\"payable\":false,\"stateMutability\":\"nonpayable\",\"type\":\"function\"}', 'function', now(), now());
-- (permission manage 0x1005) insert queryByName remove grantWrite revokeWrite
INSERT INTO `tb_function`(`method_id`, `abi_info`, `type`, `gmt_create`, `gmt_modify`) VALUES ('0xce0a9fb9', '{\"constant\":false,\"inputs\":[{\"name\":\"table_name\",\"type\":\"string\"},{\"name\":\"addr\",\"type\":\"string\"}],\"name\":\"insert\",\"outputs\":[{\"name\":\"\",\"type\":\"int256\"}],\"payable\":false,\"stateMutability\":\"nonpayable\",\"type\":\"function\"}', 'function', now(), now());
INSERT INTO `tb_function`(`method_id`, `abi_info`, `type`, `gmt_create`, `gmt_modify`) VALUES ('0xbbec3f91', '{\"constant\":true,\"inputs\":[{\"name\":\"table_name\",\"type\":\"string\"}],\"name\":\"queryByName\",\"outputs\":[{\"name\":\"\",\"type\":\"string\"}],\"payable\":false,\"stateMutability\":\"view\",\"type\":\"function\"}', 'function', now(), now());
INSERT INTO `tb_function`(`method_id`, `abi_info`, `type`, `gmt_create`, `gmt_modify`) VALUES ('0x85d23afc', '{\"constant\":false,\"inputs\":[{\"name\":\"table_name\",\"type\":\"string\"},{\"name\":\"addr\",\"type\":\"string\"}],\"name\":\"remove\",\"outputs\":[{\"name\":\"\",\"type\":\"int256\"}],\"payable\":false,\"stateMutability\":\"nonpayable\",\"type\":\"function\"}', 'function', now(), now());
INSERT INTO `tb_function`(`method_id`, `abi_info`, `type`, `gmt_create`, `gmt_modify`) VALUES ('0xd010d23c', '{\"constant\":false,\"inputs\":[{\"name\":\"contractAddr\",\"type\":\"address\"},{\"name\":\"user\",\"type\":\"address\"}],\"name\":\"grantWrite\",\"outputs\":[{\"name\":\"\",\"type\":\"int256\"}],\"payable\":false,\"stateMutability\":\"nonpayable\",\"type\":\"function\"}', 'function', now(), now());
INSERT INTO `tb_function`(`method_id`, `abi_info`, `type`, `gmt_create`, `gmt_modify`) VALUES ('0xdf12fe78', '{\"constant\":false,\"inputs\":[{\"name\":\"contractAddr\",\"type\":\"address\"},{\"name\":\"user\",\"type\":\"address\"}],\"name\":\"revokeWrite\",\"outputs\":[{\"name\":\"\",\"type\":\"int256\"}],\"payable\":false,\"stateMutability\":\"nonpayable\",\"type\":\"function\"}', 'function', now(), now());
-- (contract life cycle 0x1007)
-- getStatus unfreeze freeze grantManager queryManager revokeManager 
INSERT INTO `tb_function`(`method_id`, `abi_info`, `type`, `gmt_create`, `gmt_modify`) VALUES ('0xbca14431', '{\"constant\":true,\"inputs\":[{\"name\":\"addr\",\"type\":\"address\"}],\"name\":\"getStatus\",\"outputs\":[{\"name\":\"\",\"type\":\"uint256\"},{\"name\":\"\",\"type\":\"string\"}],\"payable\":false,\"stateMutability\":\"view\",\"type\":\"function\"}', 'function', now(), now());
INSERT INTO `tb_function`(`method_id`, `abi_info`, `type`, `gmt_create`, `gmt_modify`) VALUES ('0x61cb24c3', '{\"constant\":false,\"inputs\":[{\"name\":\"addr\",\"type\":\"address\"}],\"name\":\"unfreeze\",\"outputs\":[{\"name\":\"\",\"type\":\"int256\"}],\"payable\":false,\"stateMutability\":\"nonpayable\",\"type\":\"function\"}', 'function', now(), now());
INSERT INTO `tb_function`(`method_id`, `abi_info`, `type`, `gmt_create`, `gmt_modify`) VALUES ('0xf12c66df', '{\"constant\":false,\"inputs\":[{\"name\":\"addr\",\"type\":\"address\"}],\"name\":\"freeze\",\"outputs\":[{\"name\":\"\",\"type\":\"int256\"}],\"payable\":false,\"stateMutability\":\"nonpayable\",\"type\":\"function\"}', 'function', now(), now());
INSERT INTO `tb_function`(`method_id`, `abi_info`, `type`, `gmt_create`, `gmt_modify`) VALUES ('0x27c46414', '{\"constant\":false,\"inputs\":[{\"name\":\"contractAddr\",\"type\":\"address\"},{\"name\":\"userAddr\",\"type\":\"address\"}],\"name\":\"grantManager\",\"outputs\":[{\"name\":\"\",\"type\":\"int256\"}],\"payable\":false,\"stateMutability\":\"nonpayable\",\"type\":\"function\"}', 'function', now(), now());
INSERT INTO `tb_function`(`method_id`, `abi_info`, `type`, `gmt_create`, `gmt_modify`) VALUES ('0xa450e730', '{\"constant\":true,\"inputs\":[{\"name\":\"addr\",\"type\":\"address\"}],\"name\":\"queryManager\",\"outputs\":[{\"name\":\"\",\"type\":\"uint256\"},{\"name\":\"\",\"type\":\"address[]\"}],\"payable\":false,\"stateMutability\":\"view\",\"type\":\"function\"}', 'function', now(), now());
INSERT INTO `tb_function`(`method_id`, `abi_info`, `type`, `gmt_create`, `gmt_modify`) VALUES ('0x00c77684', '{\"constant\":false,\"inputs\":[{\"name\":\"contractAddr\",\"type\":\"address\"},{\"name\":\"userAddr\",\"type\":\"address\"}],\"name\":\"revokeManager\",\"outputs\":[{\"name\":\"\",\"type\":\"int256\"}],\"payable\":false,\"stateMutability\":\"nonpayable\",\"type\":\"function\"}', 'function', now(), now());
-- (chain governance 0x1008)
-- listOperators updateCommitteeMemberWeight queryThreshold queryCommitteeMemberWeight grantCommitteeMember
INSERT INTO `tb_function`(`method_id`, `abi_info`, `type`, `gmt_create`, `gmt_modify`) VALUES ('0xb90059a3', '{\"constant\":true,\"inputs\":[],\"name\":\"listOperators\",\"outputs\":[{\"name\":\"\",\"type\":\"string\"}],\"payable\":false,\"stateMutability\":\"view\",\"type\":\"function\"}', 'function', now(), now());
INSERT INTO `tb_function`(`method_id`, `abi_info`, `type`, `gmt_create`, `gmt_modify`) VALUES ('0x95e96f8f', '{\"constant\":false,\"inputs\":[{\"name\":\"user\",\"type\":\"address\"},{\"name\":\"weight\",\"type\":\"int256\"}],\"name\":\"updateCommitteeMemberWeight\",\"outputs\":[{\"name\":\"\",\"type\":\"int256\"}],\"payable\":false,\"stateMutability\":\"nonpayable\",\"type\":\"function\"}', 'function', now(), now());
INSERT INTO `tb_function`(`method_id`, `abi_info`, `type`, `gmt_create`, `gmt_modify`) VALUES ('0x35365efb', '{\"constant\":true,\"inputs\":[],\"name\":\"queryThreshold\",\"outputs\":[{\"name\":\"\",\"type\":\"int256\"}],\"payable\":false,\"stateMutability\":\"view\",\"type\":\"function\"}', 'function', now(), now());
INSERT INTO `tb_function`(`method_id`, `abi_info`, `type`, `gmt_create`, `gmt_modify`) VALUES ('0xc784c982', '{\"constant\":true,\"inputs\":[{\"name\":\"user\",\"type\":\"address\"}],\"name\":\"queryCommitteeMemberWeight\",\"outputs\":[{\"name\":\"\",\"type\":\"bool\"},{\"name\":\"\",\"type\":\"int256\"}],\"payable\":false,\"stateMutability\":\"view\",\"type\":\"function\"}', 'function', now(), now());
INSERT INTO `tb_function`(`method_id`, `abi_info`, `type`, `gmt_create`, `gmt_modify`) VALUES ('0xcbff0346', '{\"constant\":false,\"inputs\":[{\"name\":\"user\",\"type\":\"address\"}],\"name\":\"grantCommitteeMember\",\"outputs\":[{\"name\":\"\",\"type\":\"int256\"}],\"payable\":false,\"stateMutability\":\"nonpayable\",\"type\":\"function\"}', 'function', now(), now());
-- unfreezeAccount listCommitteeMembers updateThreshold revokeCommitteeMember grantOperator
INSERT INTO `tb_function`(`method_id`, `abi_info`, `type`, `gmt_create`, `gmt_modify`) VALUES ('0x2312386d', '{\"constant\":false,\"inputs\":[{\"name\":\"account\",\"type\":\"address\"}],\"name\":\"unfreezeAccount\",\"outputs\":[{\"name\":\"\",\"type\":\"int256\"}],\"payable\":false,\"stateMutability\":\"nonpayable\",\"type\":\"function\"}', 'function', now(), now());
INSERT INTO `tb_function`(`method_id`, `abi_info`, `type`, `gmt_create`, `gmt_modify`) VALUES ('0x77cb0994', '{\"constant\":true,\"inputs\":[],\"name\":\"listCommitteeMembers\",\"outputs\":[{\"name\":\"\",\"type\":\"string\"}],\"payable\":false,\"stateMutability\":\"view\",\"type\":\"function\"}', 'function', now(), now());
INSERT INTO `tb_function`(`method_id`, `abi_info`, `type`, `gmt_create`, `gmt_modify`) VALUES ('0x931af204', '{\"constant\":false,\"inputs\":[{\"name\":\"threshold\",\"type\":\"int256\"}],\"name\":\"updateThreshold\",\"outputs\":[{\"name\":\"\",\"type\":\"int256\"}],\"payable\":false,\"stateMutability\":\"nonpayable\",\"type\":\"function\"}', 'function', now(), now());
INSERT INTO `tb_function`(`method_id`, `abi_info`, `type`, `gmt_create`, `gmt_modify`) VALUES ('0x681362f3', '{\"constant\":false,\"inputs\":[{\"name\":\"user\",\"type\":\"address\"}],\"name\":\"revokeCommitteeMember\",\"outputs\":[{\"name\":\"\",\"type\":\"int256\"}],\"payable\":false,\"stateMutability\":\"nonpayable\",\"type\":\"function\"}', 'function', now(), now());
INSERT INTO `tb_function`(`method_id`, `abi_info`, `type`, `gmt_create`, `gmt_modify`) VALUES ('0xd1db6540', '{\"constant\":false,\"inputs\":[{\"name\":\"user\",\"type\":\"address\"}],\"name\":\"grantOperator\",\"outputs\":[{\"name\":\"\",\"type\":\"int256\"}],\"payable\":false,\"stateMutability\":\"nonpayable\",\"type\":\"function\"}', 'function', now(), now());
-- freezeAccount revokeOperator getAccountStatus
INSERT INTO `tb_function`(`method_id`, `abi_info`, `type`, `gmt_create`, `gmt_modify`) VALUES ('0x563e46a5', '{\"constant\":false,\"inputs\":[{\"name\":\"account\",\"type\":\"address\"}],\"name\":\"freezeAccount\",\"outputs\":[{\"name\":\"\",\"type\":\"int256\"}],\"payable\":false,\"stateMutability\":\"nonpayable\",\"type\":\"function\"}', 'function', now(), now());
INSERT INTO `tb_function`(`method_id`, `abi_info`, `type`, `gmt_create`, `gmt_modify`) VALUES ('0xc9ab2069', '{\"constant\":false,\"inputs\":[{\"name\":\"user\",\"type\":\"address\"}],\"name\":\"revokeOperator\",\"outputs\":[{\"name\":\"\",\"type\":\"int256\"}],\"payable\":false,\"stateMutability\":\"nonpayable\",\"type\":\"function\"}', 'function', now(), now());
INSERT INTO `tb_function`(`method_id`, `abi_info`, `type`, `gmt_create`, `gmt_modify`) VALUES ('0xa41e61cc', '{\"constant\":true,\"inputs\":[{\"name\":\"account\",\"type\":\"address\"}],\"name\":\"getAccountStatus\",\"outputs\":[{\"name\":\"\",\"type\":\"string\"}],\"payable\":false,\"stateMutability\":\"view\",\"type\":\"function\"}', 'function', now(), now());
